.gitignore
.travis.yml
README.md
coverage.ini
setup.py
src/typing.py
tests/FormatTest.py
tests/PyflakesSyntaxTest.py
tests/pulses/ConditionTests.py
tests/pulses/InstructionsTests.py
tests/pulses/ParameterTests.py
tests/pulses/SequenceTests.py
tests/pulses/SequencerTests.py
tests/run_tests.py
tests/syntax_check.py
tests/utils/TypeCheckTest.py

I've finally been able to come up with a configuration for Travis that works.
I've created a preliminary setup.py, which is used by Travis to run tests via the "setup.py test" command.
To ensure that imports in test modules work in any case (i.e. Travis and manual execution in eclipse) I had to change the way imports had been: Every test module now adds the src-folder to sys.path (instead of the concrete subfolder, e.g., src/pulses). Accordingly, imports in test modules must be made relative to that, e.g. import pulses.Parameter. This is the only solution I could come up with such that tests run in all required cases.
I also had to (temporarily) add the typing module from my Python 3.5.0b2 directory since Travis currently only features Python 3.5.0a2 which seems to no include it.
Any …

Working Travis Configuration

---

src/pulses/Plotting.py

Sequencer was intended to be used with specialized subtypes of SequencingHardwareInterface to achieve translations to different target hardware (or software) data structures without changing Sequencer itself.
Following this idea, I've changed the Plotting.py such that all meaningful calculations are done in a SequencingHardwareInterface subtype called Plotter which works with the default Sequencer and removed the classes PlottingSequencer and PlottingDummySequencingHardware (the latter of which did not do anything meaningful).

Alternative/Revised Plotting Classes

---

qctoolkit/expressions.py
tests/annotation_tests.py

This allows one to write `float(pulse.calculate_duration())`
@terrorfisch @lucblom

add convenience function to convert expression to float

---

qctoolkit/pulses/loop_pulse_template.py
qctoolkit/pulses/repetition_pulse_template.py
qctoolkit/pulses/sequence_pulse_template.py
tests/pulses/loop_pulse_template_tests.py
tests/pulses/repetition_pulse_template_tests.py
tests/pulses/sequence_pulse_template_tests.py

ForLoopPulseTemplate, SequencePulseTemplate, RepetitionPulseTemplate now also include all parameters only appearing in constraint expression in parameter_names .
Tests included.
closes #230

Fixed issue #230

---

qctoolkit/hardware/setup.py

__eq__ function does not use __hash__ anymore. Instead it uses the tuple used in __hash__ directly.
hash() is not a bijective function, different objects may have the same hash without being equal.

Fix: hardware.setup._SingleChannel.__eq__

---

tests/pulses/multi_channel_pulse_template_tests.py
tests/pulses/sequence_pulse_template_tests.py

Although the tests pass on Travis they fail on my machine. This PR simply replaces catching the warnings by hand with the unittest context manager for that.

Fix failing tests for deprecation warnings on Windows(?)

---

qctoolkit/pulses/plotting.py
tests/pulses/plotting_tests.py

It will now issue a warning and return/show an empty plot.

Fix plot() to not crash on empty pulse

---

qctoolkit/hardware/awgs/base.py
qctoolkit/hardware/dacs/__init__.py
qctoolkit/hardware/dacs/alazar.py
qctoolkit/hardware/dacs/dac_base.py
qctoolkit/hardware/setup.py
tests/hardware/dummy_devices.py
tests/hardware/setup_tests.py

I implemented this by adding an abstract clear() method to the AWG and DAC classes and a clear_programs() method to HardwareSetup which calls clear() of all known AWG and DAC instances.
The Tabor AWG implementation (TaborChannelPair) already had a clear() method. I think it does exactly what is proposed, but I'm not familiar with the Tabor API, so can someone please have a look and confirm this (@terrorfisch , @pcerf or whoever knows stuff like this).
The Alazar DAC implementation seems to store state on hardware but only keeps a dictionary of registered programs in our local code. The clear() method I implemented just clears this dict. Can someone confirm this is correct behavior?
Should be ready to merge after the above two questions are addressed.

Implementation of #247 (clearing all programs)

---

qctoolkit/pulses/function_pulse_template.py
qctoolkit/pulses/loop_pulse_template.py
qctoolkit/pulses/multi_channel_pulse_template.py
qctoolkit/pulses/point_pulse_template.py
qctoolkit/pulses/repetition_pulse_template.py
qctoolkit/pulses/sequence_pulse_template.py
qctoolkit/pulses/table_pulse_template.py
qctoolkit/serialization.py
tests/pulses/function_pulse_tests.py
tests/pulses/loop_pulse_template_tests.py
tests/pulses/multi_channel_pulse_template_tests.py
tests/pulses/point_pulse_template_tests.py
tests/pulses/repetition_pulse_template_tests.py
tests/pulses/sequence_pulse_template_tests.py
tests/pulses/sequencing_dummies.py
tests/pulses/table_pulse_template_tests.py
tests/serialization_tests.py

All PulseTemplate classes now have get_serialization_data and deserialize methods that are conformant with the new serialization routines (from the base branch) but also maintain compatability to the old routines for a transition period. Tests cover both (old and new) ways.
First step to fully integrate the changes into master. 
Still coming up (in separate pull requests):
- Fixes to tests that currently still use the old serialization routines
- Script to automatically convert old serialized pulses into new format

backward-compatible implementations of get_serialization_data and deserialize

---

qctoolkit/pulses/function_pulse_template.py
qctoolkit/pulses/loop_pulse_template.py
qctoolkit/pulses/multi_channel_pulse_template.py
qctoolkit/pulses/point_pulse_template.py
qctoolkit/pulses/pulse_template.py
qctoolkit/pulses/pulse_template_parameter_mapping.py
qctoolkit/pulses/repetition_pulse_template.py
qctoolkit/pulses/sequence_pulse_template.py
qctoolkit/pulses/table_pulse_template.py
qctoolkit/serialization.py
tests/pulses/function_pulse_tests.py
tests/pulses/loop_pulse_template_tests.py
tests/pulses/multi_channel_pulse_template_tests.py
tests/pulses/point_pulse_template_tests.py
tests/pulses/pulse_template_tests.py
tests/pulses/sequence_pulse_template_tests.py
tests/pulses/sequencing_dummies.py
tests/pulses/table_pulse_template_tests.py
tests/serialization_tests.py

- Rename pulse registration to registry
- Include in each pulse init method
- Trigger garbage collection on each pulse initialization.
- Update serialization tests to use dedicated registry dicts

Fix (global) pulse registry

---

qctoolkit/serialization.py
tests/serialization_tests.py

Closes issue #271 and closes issue #281

Fix issues 271&281

---

qctoolkit/serialization.py
tests/serialization_tests.py

Merge issue #275

---

qctoolkit/pulses/pulse_template_parameter_mapping.py
qctoolkit/pulses/sequence_pulse_template.py
qctoolkit/serialization.py
tests/pulses/pulse_template_parameter_mapping_tests.py
tests/pulses/pulse_template_tests.py
tests/pulses/sequencing_dummies.py

Fixed:
- MappingPT did not implement the new serialization (and had no dedicated serialization tests)
- Several implementations of get_serialization_data and deserialize in test dummies did not have the update signature and required a Serializer object to be passed as positional parameter

Fixes for new serialization

---

setup.py

Sympy version 1.2 results in syntax errors in tests of vectorized expressions . See issue #302

Fixed sympy version to 1.1.1

---

qctoolkit/serialization.py
tests/serialization_tests.py

Closes #294
I looked into coveralls to see which lines/branches are not yet covered by tests.
In particular the case in Serializable.__init__() where a pulse might get registered only after the gc is invoked was not covered. I tried to do this (delete a registered pulse with del while explicitely disabling the automatic gc) but couldn't cause the desired behavior. Are we sure that the invocation of the gc is necessary at that point?
Also, there's the issue of the AnonymousSerializable. It is currently not neatly integrated into the Serializable class tree and should really be (or be an abstract class defining abstract methods).

Increased test coverage for serialization

---

qctoolkit/pulses/loop_pulse_template.py
qctoolkit/pulses/mapping_pulse_template.py
qctoolkit/pulses/multi_channel_pulse_template.py
qctoolkit/pulses/pulse_template.py
qctoolkit/pulses/repetition_pulse_template.py
qctoolkit/pulses/sequence_pulse_template.py
tests/pulses/loop_pulse_template_tests.py
tests/pulses/mapping_pulse_template_tests.py
tests/pulses/multi_channel_pulse_template_tests.py
tests/pulses/pulse_template_tests.py
tests/pulses/repetition_pulse_template_tests.py
tests/pulses/sequence_pulse_template_tests.py
tests/pulses/sequencing_dummies.py

Implementations of new signature PT._internal_create_program for RepetitionPT, SequencePT, ForLoopPT, AtomicPT (and thus all subclasses of that) + tests.
MappingPT is the only one missing now.
After that is done, #287 should be finished.

Changes to (_internal_)create_program()

---

qctoolkit/pulses/pulse_template.py
qctoolkit/pulses/sequence_pulse_template.py
tests/pulses/pulse_template_tests.py
tests/pulses/sequence_pulse_template_tests.py

Currently `__matmul__` drops measurements, identifiers and parameter constraints of SequencePulseTemplates that are concatenated with it.
This is fixed here.

Fix __matmul__ bug

---

qctoolkit/serialization.py
tests/pulses/pulse_template_tests.py
tests/serialization_tests.py

- Updated docstring of Serializable to refer to PulseStorage instead of Serializer.
- Found a remaining deserialize which was stall a staticmethod instead of a classmethod in PulseTemplateStub testing code.
- Replaced references of NestedDummySerializable in tests for new serialization routines by simple DummySerializble (this will allow us to get rid of NestedDummySerializable once we ditch the old serialization routines + tests).

Some "fixes" for serialization.

---

qctoolkit/pulses/__init__.py
tests/pulses/pulse_template_parameter_mapping_tests.py

pusle_template_parameter_mapping adds a deserialization handler for MappingPTs in outdated serializations which must be present for their deserialization to succeed.
Additionally: removed reference to Serializer in a corresponding test.

Included pulses.pulse_template_parameter_mapping in pulses.__init__.py

---

qctoolkit/_program/_loop.py
qctoolkit/pulses/pulse_template.py
tests/pulses/loop_pulse_template_tests.py
tests/pulses/mapping_pulse_template_tests.py
tests/pulses/pulse_template_tests.py
tests/pulses/repetition_pulse_template_tests.py
tests/pulses/sequence_pulse_template_tests.py
tests/pulses/sequencing_dummies.py

Extended tests for _internal_create_program to check that the result is the same as doing old Sequencing and constructing MultiChannelProgram from the resulting InstructionBlock.
Fixed behavior of AtomicPulseTemplate (and DummyPulseTemplate). Added measurements to compare_key of Loop.
Differences in behavior as detected by those tests are the following:
AtomicPulseTemplate (and thus all subclasses (TablePT, PointPT, MutliChannelPT, FunctionPT)):
- behavior exactly the same
SequencePulseTemplate:
- if all subtemplates have no duration (i.e. duration of the SequencePT is 0), _internal_create_program adds nothing (no children, no waveform, no measurements) to the parent_loop. Sequencer+MCP results in empty loop with measurements from SequencePT.
RepetitionPulseTemplate:
- if repetition count …

Compatibility Tests for create_program

---

qctoolkit/pulses/loop_pulse_template.py
qctoolkit/pulses/sequence_pulse_template.py
setup.py

Increases `create_program` performance for wide charge scan by a factor of 3-4

Increase program creation performance

---

qctoolkit/serialization.py
tests/serialization_tests.py

FilesystemBackend will now create the directory given as its argument if the new create_if_missing argument is explicitely turned to True (False by default).

FilesystemBackend will now create the directory

---

qctoolkit/_program/waveforms.py
tests/__init__.py
tests/_program/waveforms_tests.py
tests/pulses/bug_tests.py

For all sub-waveform except the first one the sample_times numpy array had dtype=object instead of dtype=float64 which led to a crash applying lambdas resulting from sympy.lambdify (e.g. when sampling FunctionWaveforms).
Added a specific test case to ensure the problem does not occur again. Also added the whole initial sample code that first encountered the bug in a new test file tests/pulses/bug_tests.py now intended to collect all reported bugs.
-- lumip

Fixed a bug in SequenceWaveform.unsafe_sample() which could cause a crash

---

ReleaseNotes.txt
qupulse/serialization.py
tests/serialization_dummies.py
tests/serialization_tests.py

Implements and closes #350 .
In addition to adding `__iter__`, `__len__` and property contents to `PulseStorage`, I also implemented them for `StorageBackend` and derived classes (so `PulseStorage` can really just forward calls). Deprecated method `StorageBackend.list_contents` in favor of property `StorageBackend.contents`.

Exposing PulseStorage Contents

---

ReleaseNotes.txt
qupulse/pulses/parameters.py
tests/pulses/bug_tests.py
tests/pulses/parameters_tests.py
tests/pulses/pulse_template_tests.py

Can now (legally) pass in an Expression object or a string representing an expression without free variables as value of a ConstantParameter.
closes #363
Apparently this was already done (even with expressions with free variables) in some tests in which parameters where never evaluated so no error occured. This has been resolved.

ConstantParameter now accepts an Expression

---

ReleaseNotes.txt
doc/source/examples/12AbstractPulseTemplate.ipynb
doc/source/examples/examples.rst
qupulse/pulses/__init__.py
qupulse/pulses/abstract_pulse_template.py
tests/pulses/abstract_pulse_template_tests.py

A draft for an abstract pulse template.
The user can declare an abstract pulse template with certain properties like `defined_channels` and `parameter_names`. If the property getter of a declared property is called, the property is marked as frozen. Calling the getter of a non-declared property raises an exception.
To instantiate an abstract pulse template it has to be linked to a "real" pulse template via `link_to`. All frozen properties need to be exactly identical to the properties of the linked pulse template. This ensures that calling the getter of a property always yields the same result for the same object.
@lumip thoughts?

Abstract pulse template.

---

qupulse/pulses/table_pulse_template.py
tests/pulses/table_pulse_template_tests.py

Raise ValueError ourselves instead of relying on sympy.Max

sympy 1.4 support

---

qupulse/hardware/awgs/base.py
qupulse/hardware/awgs/tabor.py
tests/hardware/tabor_dummy_based_tests.py

The Tabor AWG has a new attribute "amplitude_offset_handling". Now it is possible to consider the offset when uploading a program to the instrument.
This pull request belongs to #446

Make offset and amplitude handling of the Tabor AWG configurable

---

ReleaseNotes.txt
qupulse/expressions.py
tests/expression_tests.py

We might have to discuss what is the desired behaviour for f-strings, but it seems reasonable to allow printing as a floating point number.
We also need to disable tests for python 3.5. Any preferred way to do this?
@terrorfisch

allow ExpressionScalar to be used in f-strings

---

qupulse/hardware/awgs/tektronix.py
tests/hardware/tektronix_tests.py

- isinstance(entry, int) in line _process_program does now handle arbitrary integer types
- `_get_empty_sequence_positions` now returns only as much free positions as asked for (+ tests)

Fix bugs in Tektronix driver

---

qupulse/pulses/plotting.py

If all pulses are constant with identical value, then `max_voltage-min_voltage` is zero and matplotlib will give a warning. This PR solves this by not updating the axis for this special case.
@terrorfisch

prevent warning when plotting constant pulses

---

setup.py
tests/utils/time_type_tests.py

This pull request adds a benchmark test for timetype which requires `pytest_benchmark` for testing.

Add time type benchmark

---

ReleaseNotes.txt
qupulse/_program/waveforms.py
qupulse/expressions.py
qupulse/hardware/dacs/alazar.py
qupulse/utils/types.py
tests/_program/loop_tests.py
tests/_program/waveforms_tests.py
tests/hardware/alazar_tests.py
tests/hardware/tektronix_tests.py
tests/hardware/util_tests.py
tests/pulses/function_pulse_tests.py
tests/pulses/multi_channel_pulse_template_tests.py
tests/pulses/sequencing_dummies.py
tests/utils/time_type_tests.py

This pull request fixes a duration value change (#475 ) when converting it from `float` to `TimeType`(arbitrary precision via fractions) by abusing `float` to `str` to get a consistent rounding.
This might lead to unexpected consequences due to float rounding errors with fractional times.
TODO:
I think the factor 2 worse performance (with gmpy) is worth the improved ergonomics.
@eendebakpt

Convert duration with full precision

---

qupulse/pulses/parameters.py
qupulse/pulses/pulse_template.py
tests/pulses/parameters_tests.py
tests/pulses/pulse_template_tests.py

- Add `__repr__` to ParameterConstraint
- Add `__repr__`, `__format__` and `__str__` to `PulseTemplate`
closes #477
TODO:

More repr implementations

---

ReleaseNotes.txt
qupulse/expressions.py
qupulse/utils/sympy.py
setup.py
tests/pulses/table_pulse_template_tests.py
tests/utils/sympy_tests.py

- Make dict a base class of IndexBasedFinder (dirty workaround)
- Do not rely on Expression('a + 3') == Expression('a + 3.'). See explanation here: https://github.com/sympy/sympy/issues/18054#issuecomment-566198899

Add support for sympy 1.5

---

qupulse/pulses/plotting.py

The plotting method issues a warning of the number of samples to be plotted is non-integer. This PR prevents issuing the warning in case of rounding errors.

improve warning for plotting of non-integer number of samples

---

qupulse/utils/types.py
tests/utils/time_type_tests.py

Use to internal to convert to mpq

---

ReleaseNotes.txt
qupulse/_program/waveforms.py
qupulse/expressions.py
qupulse/pulses/function_pulse_template.py
qupulse/pulses/table_pulse_template.py
qupulse/utils/sympy.py
qupulse/utils/types.py
tests/expression_tests.py
tests/utils/sympy_tests.py
tests/utils/time_type_tests.py

Before this PR Rational objects in sympy expressions where evaluated as floats upon numeric evaluation. This PR adds `ScalarExpression.evaluate_with_exact_rationals` which is used for example in TablePT and FunctionPT to evaluate time expressions.

Keep TimeType precision if they are used in Expressions

---

qupulse/pulses/pulse_template.py

Users shouldnt be required to implement a method that is not used yet and which will probably change in the future.
@peendebak That should fix your issue

AtomicPulseTemplate._as_expression is no longer abstract

---

qupulse/expressions.py
qupulse/pulses/parameters.py
qupulse/serialization.py
setup.cfg
tests/backward_compatibility/tabor_backward_compatibility_tests.py
tests/expression_tests.py
tests/hardware/zihdawg_tests.py
tests/pulses/mapping_pulse_template_tests.py
tests/pulses/parameters_tests.py
tests/pulses/pulse_template_tests.py
tests/pulses/repetition_pulse_template_tests.py
tests/pulses/sequence_pulse_template_tests.py
tests/serialization_tests.py

- Configure pytest to fail on any `DeprecationWarning`
- Fix warning by sympy by adding explicit `Expression._sympy_`
- Ignore a warning that is emitted by a pytest dependency

Fail tests on deprecation warnings

---

qupulse/hardware/util.py

This PR improves sampling speed of the `get_sample_times` method.
```
%timeit np.arange(10000)/2.4
21 µs ± 132 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)
%timeit np.arange(0, 10000/2.4, 1/2.4)
6.81 µs ± 28.2 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
a=np.arange(10000)/2.4
b=np.arange(0, 10000/2.4, 1/2.4)
a-b
Out[184]: array([0., 0., 0., ..., 0., 0., 0.])
np.max(np.abs(a-b))
Out[185]: 0.0
```
@terrorfisch

performance improvement for sampling

---

.travis.yml

Add python 3.8 to CI. We have used qupulse locally with python 3.8 for some time now.

add python 3.8 to CI

---

qupulse/hardware/awgs/tektronix.py
qupulse/hardware/feature_awg/base.py
qupulse/hardware/feature_awg/tabor.py
qupulse/hardware/util.py
qupulse/pulses/table_pulse_template.py
qupulse/utils/__init__.py
qupulse/utils/types.py
tests/_program/seqc_tests.py
tests/hardware/feature_awg/awg_new_driver_base_tests.py
tests/utils/types_tests.py

A custom `Collection` is no longer required because python 3.5 support was dropped.
A few tests relied on bad hashing behaviour of tuples which was fixed in python 3.8
https://bugs.python.org/issue34751
This PR fixes those tests.
Remove an overlooked more_itertools function call on which we no longer depend
https://github.com/qutech/qupulse/commit/651335619f40e2c6b443171515d8fc6bb82da417

Remove typing.Collection backport and improve python 3.8 support

---

qupulse/hardware/util.py

Method is refactored so we can get the waveform length without generating the full `time_array` array
@terrorfisch

refactor get_sample_times method

---

qupulse/_program/waveforms.py
qupulse/utils/sympy.py

For our waveforms we need different values for some of the error margins. This PR makes them configurable.
```
In [1]: import qupulse.utils.sympy
...: from qupulse.utils.sympy import almost_equal
...: print(qupulse.utils.sympy.SYMPY_DURATION_ERROR_MARGIN)
...: print(almost_equal(0, 1e-14))
...: 
...: qupulse.utils.sympy.SYMPY_DURATION_ERROR_MARGIN=1e-6
...: 
...: print(qupulse.utils.sympy.SYMPY_DURATION_ERROR_MARGIN)
...: print(almost_equal(0, 1e-14))
1e-15
False
1e-06
True
```
@terrorfisch

Feature variable error margins

---

qupulse/pulses/arithmetic_pulse_template.py

We combine the measurement windows from the `lhs` and `rhs` if these are templates. For expressions or numbers there are no windows.
@terrorfisch

add measurement windows for pulse arithmetic

---

setup.cfg

The PEP517 build did not include any packages because the `find` include argument was specified with space as delimiter.
@peendebak

Fix pip install from git

---

qupulse/pulses/repetition_pulse_template.py
tests/pulses/repetition_pulse_template_tests.py
tests/pulses/sequencing_dummies.py

Previously it returned a list. Why could this be overlooked so long?

Fix RepetitionPT.integral return type

---

ReleaseNotes.txt
doc/source/examples/03ConstantPulseTemplate.ipynb
qupulse/_program/waveforms.py
qupulse/pulses/__init__.py
qupulse/pulses/constant_pulse_template.py
tests/_program/waveforms_tests.py
tests/pulses/constant_pulse_template_tests.py

Add template for multi-channel pulses that are constant. These pulses are easier to create than a `TablePulseTemplate` and allow backends to optimize uploaded of these waveforms.
@terrorfisch

Add ConstantPulseTemplate

---

changes.d/622.feature
qupulse/_program/_loop.py
qupulse/_program/seqc.py
qupulse/_program/volatile.py
qupulse/utils/numeric.py
tests/_program/loop_tests.py
tests/_program/seqc_tests.py
tests/utils/numeric_tests.py

- New function `qupulse._program._loop.roll_constant_waveforms` that can transform long constant waveforms into repetitions of shorter waveforms.
- The sample rate of HDAWG playbacks can now be dynamically reduced. Currently this can be enabled with the class attribute `qupulse._program.seqc.WaveformPlayback.ENABLE_DYNAMIC_RATE_REDUCTION`. #622
[Tests pass](https://github.com/qutech/qupulse/runs/4242052498)
Todo:

Dynamic loop insertion

---

qupulse/_program/transformation.py
qupulse/pulses/plotting.py
qupulse/utils/sympy.py
tests/_program/seqc_tests.py
tests/backward_compatibility/tabor_backward_compatibility_tests.py
tests/hardware/feature_awg/awg_new_driver_base_tests.py
tests/hardware/feature_awg/channel_tuple_wrapper_tests.py
tests/hardware/feature_awg/tabor_new_driver_simulator_based_tests.py
tests/hardware/feature_awg/tabor_new_driver_tests.py
tests/hardware/tabor_simulator_based_tests.py
tests/hardware/tabor_tests.py
tests/hardware/tektronix_tests.py
tests/hardware/zihdawg_tests.py
tests/utils/sympy_tests.py

- skip hardware related tests if requirements are not installed
- Adhere to some new deprecations in numpz and distutils
- Improve a few warnings by passing a more useful stacklevel

Fix some unittest issues and deprecations

---

qupulse/pulses/interpolation.py
qupulse/pulses/table_pulse_template.py
tests/pulses/sequencing_dummies.py

This PR improves the efficiency of calculation of integrals for the TablePulseTemplate. If there are no free variables in the TablePulseTemplate this calculation can be done even more efficiently, but this is not implemented in this PR.
- Lambdify integral expressions
- Use class variables for the expression and integral
- Reduce double evaluations in the TableEntry._sequence_integral
@terrorfisch

improve efficiency of TablePulseTemplate integral

---

qupulse/expressions.py

The casting to float for an `ExpressionScalar` is an expensive operation. This PR specializes the `__float__` method to return the underlying expression in case the `ExpressionScalar` was constructed from a `float` .
@terrorfisch

specialization to cast an expressionscalar to a float

---

qupulse/expressions.py

Specialization for float and int in expressionscalar constructor. This avoid calling the on the `get_variables`. One more optimization would be to make the `_sympified_expression` a lazy evaluation.
@terrorfisch

specialization for float and int in expressionscalar constructor

---

changes.d/639.removal
qupulse/_program/volatile.py
qupulse/parameter_scope.py
qupulse/utils/types.py
setup.cfg

Use frozendict package which includes a C extension instead of self-written python code. The `frozendict` creation is roughly 5 times faster on my machine.
We keep the hand rolled code around until the next release so we do not break code.
TODO:
Performance influence:
-  on my machine 3% improvement of 
```
ppt = PointPT([(0, 'i'), (1, 'i')], ('a',))
fpt = ForLoopPT(ppt, 'i', 'n')
fpt.create_program(parameters=dict(n=10000))```

Use frozendict package

---

qupulse/pulses/plotting.py

This improves performance together with https://github.com/numpy/numpy/pull/21832
The argument is not required, since `start` and `stop` are cast to float.
@terrorfisch

Remove redundant linspace argument

---

qupulse/expressions.py

For operators like `>` or `==` it is more efficient to let sympy do the conversion of non-sympy types. For types like `int` and `float` sympy can optimize.
@terrorfisch

Improve performance of expressionscalar operations

---

qupulse/pulses/function_pulse_template.py

FunctionPT.build_waveform should return ConstantWaveform now if the expressions evaluates to a constant value. This was an oversight in earlier changes.
@peendebak Should fix your warning problem and result in more performant programs.

Make FunctionPT.build_waveform use from_expression

---

qupulse/_program/transformation.py

This PR reduces the qupulse import time by almost a second by skipping the import of `pandas`.
The code could be simplified if we skip the type annotation for the `linear_transformation_from_pandas` method.
@terrorfisch

Prevent pandas import at startup

---

qupulse/pulses/constant_pulse_template.py
tests/pulses/constant_pulse_template_tests.py

Add explicit expression support to ConstantPulseTemplate with a fast path for float. Add extensive testing, serialize measurement windows and honor the pulse registry.
@eendebakpt This should not lead to a measurable slow down. Please check if you have concerns with this

Cleanup ConstantPT and extend capabilities

---

changes.d/696.fix
qupulse/pulses/constant_pulse_template.py
tests/pulses/constant_pulse_template_tests.py

Fix legacy deserialization

---

changes.d/709.feature
qupulse/_program/transformation.py
qupulse/pulses/__init__.py
qupulse/pulses/arithmetic_pulse_template.py
qupulse/pulses/mapping_pulse_template.py
qupulse/pulses/multi_channel_pulse_template.py
qupulse/pulses/pulse_template.py
qupulse/pulses/time_reversal_pulse_template.py
qupulse/utils/types.py
tests/_program/transformation_tests.py
tests/pulses/arithmetic_pulse_template_tests.py
tests/pulses/multi_channel_pulse_template_tests.py

The original idea was to enable time dependent expressions for arithmetic pulse templates. However this will not produce reasonable results when the other PT is not atomic because the waveform i.e. the transformation will not get the correct time during sampling of a composite PT.
One could circumvent this by adding a time delay for SequencePT and ForLoopPT but if there is a RepetitionPT it cannot be handled correctly because the waveform itself is not actually repeated i.e. it needs to be unrolled.
We could adapt the `Program` type to be more powerful and cover the representation of a modulated or otherwise altered sub-program. This could allow efficient playback on supporting hardware.
The current solution is to enforce atomicity via the newly added `_is_atomic` method.
Examples will be …

Add support for time dependent expressions in transformations.

---

changes.d/710.feature
qupulse/pulses/multi_channel_pulse_template.py
qupulse/pulses/parameters.py
qupulse/pulses/pulse_template.py
qupulse/pulses/repetition_pulse_template.py
qupulse/pulses/sequence_pulse_template.py
qupulse/pulses/time_reversal_pulse_template.py
tests/pulses/pulse_template_tests.py

Documentation is handled in a different PR and tracked via the issue #710

Add pulse template creation helpers

---

RELEASE_NOTES.rst
changes.d/512.removal
changes.d/696.fix
changes.d/703.feature
changes.d/709.feature
changes.d/710.feature
changes.d/735.feature
changes.d/760.removal
qupulse/__init__.py
setup.cfg

Prepare release of 0.8

---

qupulse/_program/seqc.py
tests/_program/seqc_tests.py

Only relevant for debugging
Factored out from #683

HDAWG: Right align channel 2 marker data in binary waveform

---

qupulse/program/waveforms.py

In `unsafe_sample` the `sample_times` is guaranteed to be a numpy array. Calling `searchsorted` from the array is more efficient.
For a small numpy array:
```
In [66]: %timeit sample_times.searchsorted( (0,0), 'left')
1.53 µs ± 63.9 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)
In [67]: %timeit np.searchsorted(sample_times, (0,0), 'left')
2.73 µs ± 424 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
```
@terrorfisch

Optimize unsafe_sample

---

qupulse/_program/tabor.py
tests/_program/tabor_tests.py
tests/pulses/sequencing_dummies.py

Tabor segment deduplication

---

qupulse/expressions/sympy.py
tests/expressions/expression_tests.py

The floordiv is required by the protocol.

Add floordiv implementation to sympy expression wrapper

---

changes.d/801.feature
qupulse/pulses/pulse_template.py
tests/pulses/pulse_template_tests.py

Add PulseTemplate.pad_to

---

qupulse/utils/__init__.py
tests/utils/utils_tests.py

could also be put somewhere else.
(Tests won't work here because floordiv not yet implemented in this branch)

Exemplary to_next_multiple

---

tests/utils/time_type_tests.py

Disable import hacking during testing which easily breaks and is only a convenience functionality for developing

Only trigger import hacking on manual request

---

doc/source/examples/04ZurichInstrumentsSetup.ipynb

Do not execute hardware dependent notebook when building docs

Fix documentation build: Hardware notebook

---

qupulse/comparable.py
qupulse/hardware/awgs/base.py
qupulse/program/transformation.py
qupulse/program/waveforms.py
tests/_program/transformation_tests.py
tests/_program/waveforms_tests.py
tests/comparable_tests.py
tests/pulses/arithmetic_pulse_template_tests.py
tests/pulses/sequence_pulse_template_tests.py
tests/pulses/sequencing_dummies.py

Deprecate comparable because it is "unpythonic" and makes comparisons hard to follow.
Three subclasses have been changed:
- `AWG` now directly implements an `id` based hash and comparison.
- `Waveform` is now compared and hashed based on the `__slots__` and `_duration` of the base class by default. `TransformingWaveform` overrides that because it caches results for more efficient multi channel sampling.
- `Transformation` implementations now provide there own `__eq__` and `__hash__`.

Deprecate Comparable

---

.github/workflows/pythontest.yaml
README.md
changes.d/835.removal
pyproject.toml
tests/serialization_tests.py

Push minimal supported python version

---

changes.d/853.misc
qupulse/utils/types.py
tests/utils/types_tests.py

Remove dead custom frozendict implementations

---

qupulse/program/linspace.py
tests/program/linspace_tests.py

Implements #860 
This acts as a failing test for #857 "offby one jump back increment" and includes the fix from #858

Add simulator for linspace program

---

qupulse/expressions/sympy.py
qupulse/program/linspace.py
qupulse/program/waveforms.py
tests/expressions/expression_tests.py
tests/program/linspace_tests.py
tests/pulses/time_reversal_pulse_template_tests.py

Add test and implementation for TimeReversalPulseTemplate ProgramBuilder support

---

qupulse/program/linspace.py
tests/program/linspace_tests.py

Test is not finished yet as command structure will be more complicated possibly.
This does not even translate to commands for me however; error in
`assert len(self.iterations) == len(previous.iterations)`, `linspace.py:330`
I believe to reproduce one needs multiple channels, and an iteration over a sequence of two pulses, one of which has a dependent value of the outer iteration, the other is another iteration over some inner loop (possibly with the outer dependency on another channel or so).

complicated test for linspacebuilder

---

README.md
doc/source/concepts/awgs.rst
doc/source/concepts/instantiating.rst
doc/source/concepts/program.rst
doc/source/concepts/pulsetemplates.rst
qupulse/_program/__init__.py
qupulse/program/__init__.py
qupulse/program/linspace.py

Improve ProgramBuilder documentation

---

changes.d/578.feature
qupulse/pulses/loop_pulse_template.py
qupulse/pulses/mapping_pulse_template.py
qupulse/pulses/pulse_template.py
qupulse/pulses/repetition_pulse_template.py
qupulse/pulses/sequence_pulse_template.py
tests/pulses/loop_pulse_template_tests.py
tests/pulses/mapping_pulse_template_tests.py
tests/pulses/repetition_pulse_template_tests.py
tests/pulses/sequence_pulse_template_tests.py

This PR adds a `to_single_waveform` argument to `PulseTemplate` which makes it translate itself into a single waveform on program creation.
Furthermore these pulse templates for ward the kwarg:
- `SequencePT`
- `RepetitionPT`
- `ForLoopPT`.
- `MappingPT`
Closes #578 
Enables #882 
Documentation is moved to #894

Add to_single_waveform property to PulseTemplate

---

qupulse/utils/sympy.py
tests/utils/sympy_tests.py

Use SciPyPrinter for sympy expression lambdification if scipy is available

---

qupulse/program/linspace.py
qupulse/program/loop.py
qupulse/program/volatile.py

Warn if volatility is not respected in Linspace builder

---

changes.d/882.feature
changes.d/882.removal
doc/source/concepts/pulsetemplates.rst
qupulse/pulses/pulse_template.py
tests/pulses/pulse_template_tests.py

A qupulsy replacement for https://github.com/qutech/qupulse/blob/feat/linspace_measurements_reversed_registers_divisor/qupulse/pulses/pulse_template.py#L637
Implements #882 
TODO:

Add more sophisticated padding support and helper functions for that

---

qupulse/utils/__init__.py
tests/utils/utils_tests.py

ExpressionScalars seem to omit brackets even if supplied in their definition; `to_next_multiple ` therefore could fail

pad expression brackets
