qutech/qupulse

src/pulses/Condition.py
src/pulses/Sequencer.py
tests/pulses/ConditionTests.py
tests/pulses/SequencerTests.py

Implements issue #39. Tests are present.
Any discussion is welcome.

Issue 39 sequencer

---

src/pulses/BranchPulseTemplate.py
src/pulses/Condition.py
src/pulses/Instructions.py
src/pulses/LoopPulseTemplate.py
src/pulses/Parameter.py
src/pulses/PulseTemplate.py
src/pulses/SequencePulseTemplate.py
src/pulses/TablePulseTemplate.py
src/utils/type_check.py

Make the trivial changes to Google style docstrings

---

src/pulses/Instructions.py
src/pulses/Parameter.py
src/pulses/TablePulseTemplate.py
tests/pulses/ConditionTests.py
tests/pulses/ParameterTests.py
tests/pulses/SequencerTests.py
tests/pulses/SequencingDummies.py
tests/pulses/TablePulseTemplateTests.py
tests/pulses/__init__.py

Complete test coverage of TablePulseTemplate, including fixes (also for related classes). Rebased onto current master, should fast-forward merge.

Issue 30 table tests

---

src/pulses/Instructions.py
src/pulses/Plotting.py
src/pulses/PulseTemplate.py
src/pulses/Sequencer.py
src/pulses/TablePulseTemplate.py
tests/pulses/InstructionsTests.py
tests/pulses/PlottingTests.py
tests/pulses/SequencePulseTemplateTests.py
tests/pulses/SequencerTests.py
tests/pulses/SequencingDummies.py
tests/pulses/TablePulseTemplateTests.py

Moved interpolation of waveforms into the Waveform class to increase flexibility.

Issue 57 interpolation sequencer

---

src/pulses/RepetitionPulseTemplate.py
tests/pulses/ParameterTests.py
tests/pulses/RepetitionPulseTemplateTests.py
tests/pulses/SequencePulseTemplateTests.py
tests/pulses/SequencingDummies.py
tests/pulses/TablePulseTemplateTests.py
tests/pulses/__init__.py

New PulseTemplate (wrapper) class to allow repeating PulseTemplates without the overhead of LoopPulseTemplate and Conditions.

Repetition

---

MATLAB/convert_qctoolkit.m
MATLAB/qctoolkitExample.m
qctoolkit/qcmatlab/manager.py
qctoolkit/qcmatlab/pulse_control.py
tests/pulses/sequencing_dummies.py
tests/qcmatlab/pulse_control_tests.py

Implementation of the proposal in issue #89 .
Comes with a usage example in the MATLAB folder of the repository.
Please check and merge, if okay. Discard otherwise.
@ekammerloher @pbethke @hbluhm @pcerf @terrorfisch

Alternative Approach to MATLAB Interaction

---

qctoolkit/pulses/parameters.py
qctoolkit/pulses/sequence_pulse_template.py
qctoolkit/pulses/table_pulse_template.py
tests/pulses/parameters_tests.py
tests/pulses/sequence_pulse_template_tests.py
tests/pulses/sequencing_dummies.py
tests/pulses/table_pulse_template_tests.py
tests/pulses/table_sequence_sequencer_intergration_tests.py

Fixes for Some Bugs and Misbehavior

---

doc/source/concepts/serialization.rst
doc/source/qctoolkit.pulses.rst
doc/source/qctoolkit.rst
pylint.rc
qctoolkit/comparable.py
qctoolkit/expressions.py
qctoolkit/pulses/branch_pulse_template.py
qctoolkit/pulses/conditions.py
qctoolkit/pulses/function_pulse_template.py
qctoolkit/pulses/instructions.py
qctoolkit/pulses/interpolation.py
qctoolkit/pulses/loop_pulse_template.py
qctoolkit/pulses/parameters.py
qctoolkit/pulses/plotting.py
qctoolkit/pulses/pulse_template.py
qctoolkit/pulses/repetition_pulse_template.py
qctoolkit/pulses/sequence_pulse_template.py
qctoolkit/pulses/sequencing.py
qctoolkit/pulses/table_pulse_template.py
qctoolkit/qcmatlab/pulse_control.py
qctoolkit/serialization.py
tests/comparable_tests.py
tests/expression_tests.py
tests/format_tests.py
tests/pulses/function_pulse_tests.py
tests/pulses/sequence_pulse_template_tests.py
tests/pulses/sequencing_dummies.py
tests/pulses/table_pulse_template_tests.py
tests/serialization_dummies.py
tests/serialization_tests.py

Added docstrings for all relevant methods, classes and modules.

Docstrings

---

qctoolkit/pulses/function_pulse_template.py
tests/pulses/function_pulse_tests.py

(except obsolete get_measurement_windows method).
Closes #119

Tests for FunctionPulseTemplate

---

qctoolkit/pulses/branch_pulse_template.py
qctoolkit/pulses/function_pulse_template.py
tests/pulses/branch_pulse_template_tests.py
tests/pulses/function_pulse_tests.py
tests/pulses/sequencing_dummies.py

full functionality and tests for BranchPulseTemplate

Branch template completion

---

qctoolkit/hardware/setup.py
tests/hardware/setup_tests.py

More flexible measurement -> mask mapping

---

qctoolkit/expressions.py
qctoolkit/pulses/function_pulse_template.py
qctoolkit/pulses/loop_pulse_template.py
qctoolkit/pulses/parameters.py
qctoolkit/pulses/repetition_pulse_template.py
qctoolkit/pulses/table_pulse_template.py
qctoolkit/serialization.py
qctoolkit/utils/sympy.py
qctoolkit/utils/types.py
setup.py
tests/expression_tests.py
tests/format_tests.py
tests/pulses/parameters_tests.py
tests/pulses/sequencing_dummies.py
tests/pulses/table_pulse_template_tests.py
tests/serialization_tests.py

#157 
Serializing of MappingPT with inserted ndim parameters

ND Array Expressions

---

qctoolkit/hardware/awgs/tabor.py
qctoolkit/pulses/pulse_template.py
qctoolkit/pulses/pulse_template_parameter_mapping.py
qctoolkit/utils/tree.py
tests/annotation_tests.py
tests/pulses/sequence_pulse_template_tests.py

- Allow parameter duplications in __matmul__
- More sophisticated annotation checker

Allow parameter duplications in __matmul__

---

qctoolkit/pulses/loop_pulse_template.py
qctoolkit/pulses/pulse_template.py
qctoolkit/pulses/repetition_pulse_template.py
tests/pulses/loop_pulse_template_tests.py
tests/pulses/repetition_pulse_template_tests.py

Measurements and parameter constraints for ForLoopPT

---

qctoolkit/pulses/table_pulse_template.py
tests/pulses/table_pulse_template_tests.py

further optimizations

---

qctoolkit/pulses/plotting.py
tests/pulses/plotting_tests.py

FIX: plotting now no longer crashes on MEASInstructions; Improved tests

---

qctoolkit/utils/sympy.py

Do not modify dict with substitutions in substitute with eval

---

MATLAB/+qc/array2list.m
MATLAB/+qc/array2row.m
MATLAB/+qc/join_params_and_dicts.m
MATLAB/+qc/load_dict.m
MATLAB/+qc/plot_pulse.m
MATLAB/+qc/save_dict.m

Update MATLAB files from triton_200/master

---

qctoolkit/pulses/plotting.py

Add maximum_points parameter to plotting to avoid accidentally

---

qctoolkit/comparable.py
qctoolkit/hardware/awgs/base.py
qctoolkit/pulses/instructions.py
qctoolkit/pulses/pulse_template.py
qctoolkit/serialization.py

Replaced them with the correct annotations.

Removed deprecated @abstractproperty and @abstractstaticmethod annotations

---

qctoolkit/pulses/loop_pulse_template.py
tests/pulses/loop_pulse_template_tests.py

ForLoopPulseTemplate warnings for loop index constraints

---

qctoolkit/pulses/repetition_pulse_template.py

Updated docstring for RepetitionPulseTemplate.

---

qctoolkit/hardware/program.py
tests/hardware/program_tests.py

Bugfix: raise instruction block error in correct position

Fix crash caused by empty REPJ

---

MATLAB/+qc/get_pulse_params.m
MATLAB/+qc/load_dict.m
MATLAB/+qc/pulse_seq.m
MATLAB/+qc/qctoolkitTestSetup.m

Triton 200/master

---

tests/serialization_tests.py

Add test for __delitem__

---

qctoolkit/_program/_loop.py
qctoolkit/_program/transformation.py
qctoolkit/pulses/loop_pulse_template.py
qctoolkit/pulses/mapping_pulse_template.py
qctoolkit/pulses/pulse_template.py
qctoolkit/pulses/repetition_pulse_template.py
qctoolkit/pulses/sequence_pulse_template.py
qctoolkit/utils/types.py
tests/_program/transformation_tests.py
tests/pulses/loop_pulse_template_tests.py
tests/pulses/mapping_pulse_template_tests.py
tests/pulses/pulse_template_tests.py
tests/pulses/repetition_pulse_template_tests.py
tests/pulses/sequence_pulse_template_tests.py
tests/pulses/sequencing_and_create_program_tests.py
tests/pulses/sequencing_dummies.py
tests/serialization_tests.py

Only allow a transformation which is applied to all waveforms as a first step. This is sufficient for crosstalk compensation.

More minimalistic and restricted approach for transformation

---

qctoolkit/hardware/awgs/tabor.py
tests/hardware/tabor_tests.py

Add functionality do disassemble tabor segments

Better tabor inspection

---

qctoolkit/pulses/plotting.py

More control over how the pulse is plotted

More flexible plotting

---

qupulse/utils/sympy.py
setup.py
tests/expression_tests.py

Fixed sympy.IndexBasedFinder to work with sympy versions 1.1.1 - 1.3 .

Compatibility for sympy 1.3

---

ReleaseNotes.txt
qupulse/serialization.py
tests/serialization_tests.py

Deprecated CachingBackend

---

qupulse/utils/types.py
tests/utils/time_type_tests.py

Add an explicit creation of the time type from nominator and denominator

---

README.md
doc/README.md

Replace qctoolkit with qupulse in README

---

qupulse/pulses/multi_channel_pulse_template.py

fix exception message in ChannelMappingException

---

.travis.yml

Use the builtin python

---

qupulse/pulses/table_pulse_template.py

fix import warning, see https://github.com/sympy/sympy/issues/15536

---

qupulse/pulses/parameters.py

Fix for new sympy

---

.gitignore
qupulse/_program/tabor.py
qupulse/hardware/feature_awg/base.py
qupulse/hardware/feature_awg/base_features.py
qupulse/hardware/feature_awg/channel_tuple_wrapper.py
qupulse/hardware/feature_awg/features.py
qupulse/hardware/feature_awg/tabor.py
tests/hardware/feature_awg/awg_new_driver_base_tests.py
tests/hardware/feature_awg/channel_tuple_wrapper_tests.py
tests/hardware/feature_awg/tabor_new_driver_clock_tests.py
tests/hardware/feature_awg/tabor_new_driver_dummy_based_tests.py
tests/hardware/feature_awg/tabor_new_driver_exex_test.py
tests/hardware/feature_awg/tabor_new_driver_simulator_based_tests.py
tests/hardware/feature_awg/tabor_new_driver_tests.py

New abstraction based on features + implementation for tabor + tests.
Written by @bpapajewski

New awg abstraction

---

qupulse/pulses/sequence_pulse_template.py

improve error message of SequencePulseTemplate

---

qupulse/_program/waveforms.py

fix corner case for sample_times of length 1

---

changes.d/592.removal
doc/source/examples/_LegacySerialization.ipynb
qupulse/pulses/multi_channel_pulse_template.py
qupulse/pulses/sequence_pulse_template.py
tests/pulses/multi_channel_pulse_template_tests.py
tests/pulses/sequence_pulse_template_tests.py

Remove external_parameters

---

qupulse/_program/waveforms.py

improve error message for SequenceWaveform

---

changes.d/604.bugfix
qupulse/expressions.py
tests/expression_tests.py
tests/pulses/arithmetic_pulse_template_tests.py

Opened new pr to test travis.com migration

Fix expression repr

---

changes.d/408.removal
qupulse/utils/types.py
tests/utils/types_tests.py

Fixes #480. Branch has wrong name

Deprecate HashableNumpyArray

---

qupulse/pulses/measurement.py

Clarify MeasurementDefiner scope in documentation

---

changes.d/615.feature
qupulse/utils/sympy.py
tests/utils/sympy_tests.py

Issues/615 sympy 1.9

---

qupulse/_program/waveforms.py
qupulse/pulses/constant_pulse_template.py

@terrorfisch One more optimization. This eliminates multiple conversions of a duration to a TimeType.

optimize waveform construction

---

qupulse/_program/waveforms.py
qupulse/pulses/constant_pulse_template.py
qupulse/utils/types.py
tests/_program/waveforms_tests.py
tests/pulses/constant_pulse_template_tests.py
tests/pulses/sequencing_dummies.py
tests/pulses/table_pulse_template_tests.py

- Make it a `__slots__` class for lower memory footprint.
- Calculate `duration` upon construction.

Improve performance of Waveform class

---

changes.d/645.feature
qupulse/expressions.py
qupulse/utils/sympy.py
tests/expression_tests.py
tests/hardware/zihdawg_tests.py
tests/utils/sympy_tests.py

Make qupulse sympy 1.10 compatible and make all expressions hashable

---

.github/workflows/pythontest.yaml
.travis.yml
changes.d/656.removal
setup.cfg

Drop python 3.6 support

---

qupulse/expressions.py

Cast np.float64 to float in ExpressionScalar initialization

---

qupulse/pulses/plotting.py
tests/pulses/plotting_tests.py

Allow plotting of pulses without specifying the samplerate
@terrorfisch

Add plotting with automatic samplerate selection

---

qupulse/pulses/plotting.py

Fix mpl warning in jupyter notebook

---

qupulse/_program/waveforms.py
qupulse/utils/types.py

Improve performance of pulse rendering

---

qupulse/_program/waveforms.py
qupulse/pulses/function_pulse_template.py

Use custom warning for constant FunctionPT

---

qupulse/pulses/arithmetic_pulse_template.py
qupulse/pulses/constant_pulse_template.py
qupulse/pulses/multi_channel_pulse_template.py
qupulse/pulses/pulse_template.py
tests/pulses/arithmetic_pulse_template_tests.py

Fix constant TransformingWaveform creation

---

changes.d/686.feature
qupulse/hardware/dacs/alazar.py
qupulse/hardware/dacs/alazar2.py
qupulse/utils/performance.py
tests/hardware/alazar_tests.py
tests/utils/performance_tests.py

Add an alazar interface that uses config2

---

qupulse/pulses/loop_pulse_template.py
qupulse/pulses/range.py
tests/pulses/loop_pulse_template_tests.py

Move parameterized range related code to separate module

---

changes.d/707.fix
qupulse/_program/waveforms.py
tests/_program/waveforms_tests.py

Fixed that single segment tables where always interpreted to be constant.
Fixes #707

Fix single segment tables

---

qupulse/pulses/repetition_pulse_template.py
tests/pulses/repetition_pulse_template_tests.py

Fix `RepetitionPT.parameter_names` set union

Fix set union

---

doc/source/examples/03SnakeChargeScan.ipynb

@BrllsRX I will push some editorial changes here for you to review

Editorial changes

---

qupulse/plotting.py

Replace plt.get_cmap with colormaps.get_cmap if available

---

qupulse/pulses/parameters.py

Use custom sympify hack in ParameterConstraint init

---

changes.d/775.fix
qupulse/pulses/arithmetic_pulse_template.py

Add pulse registry support for ArithmeticPT

---

changes.d/692.feature
qupulse/pulses/pulse_template.py
tests/pulses/pulse_template_tests.py

Add __pow__ convenience repetition operation.

---

qupulse/pulses/pulse_template.py

Fix overflow due to pyint to int32 conversion

---

.github/workflows/pythontest.yaml

https://github.com/qutech/qupulse/actions/runs/6339934306

Remove gmpy build dependencies in CI

---

qupulse/plotting.py

Avoid warning on interactive plotting in Jupyter

---

changes.d/808.doc
doc/source/examples/04ZurichInstrumentsSetup.ipynb
qupulse/hardware/setup.py
qupulse/plotting.py
qupulse/program/transformation.py
qupulse/program/waveforms.py

Exemplary zurich instruments hardware setup

---

.zenodo.json

Add zenodo metadata

---

doc/source/concepts/program.rst
qupulse/program/__init__.py
qupulse/program/loop.py
qupulse/pulses/plotting.py

Better than before. Not sufficient yet. Todo: update "isntanting.rst"

Improvements of program documentation

---

.github/workflows/pythontest.yaml
changes.d/845.removal
qupulse/hardware/awgs/tabor.py
qupulse/utils/types.py
setup.cfg
tests/utils/time_type_tests.py

Make gmpy2 a hard dependency

---

qupulse/program/__init__.py
qupulse/program/loop.py
qupulse/program/waveforms.py
qupulse/pulses/time_reversal_pulse_template.py
tests/pulses/time_reversal_pulse_template_tests.py

This branch does not include the linspace implementation of #865

Partial fast mergable fix for time reversal

---

.github/workflows/pythontest.yaml
pyproject.toml
qupulse/expressions/sympy.py
qupulse/utils/sympy.py
qupulse/utils/types.py
tests/_program/transformation_tests.py
tests/expressions/expression_tests.py

This PR fixes tests and makes the runnable out of the box with `python -m hatch test`.
@Nomos11 This PR changes the sympy based Expression equality behavior to be consistent with other numerics. Probably not the final iteration

Fix tests and make hatch test usable

---

doc/source/concepts/pulsetemplates.rst

Add section about PT convenience functionality

---

.github/workflows/pythonpublish.yml

Update actions and python version in pythonpublish.yml

---

doc/source/conf.py
qupulse/program/loop.py
qupulse/program/protocol.py
qupulse/program/transformation.py
qupulse/program/values.py
qupulse/pulses/loop_pulse_template.py
qupulse/pulses/mapping_pulse_template.py
qupulse/pulses/parameters.py
qupulse/pulses/pulse_template.py
qupulse/pulses/repetition_pulse_template.py
qupulse/pulses/sequence_pulse_template.py
tests/pulses/repetition_pulse_template_tests.py
tests/pulses/sequence_pulse_template_tests.py

Rework PT docstrings
